models/innlegg.py
from datetime import datetime
from typing import List

from flask import abort, url_for
from mysql.connector import Error

from extensions import db
from models.blog import Blog
from models.bruker import Bruker
from models.kommentar import Kommentar
from models.tag import Tagger
from models.vedlegg import Vedlegg


class Innlegg:
    def __init__(self,
                 innlegg_id: int = None,
                 innlegg_tittel: str = None,
                 innlegg_innhold: str = None,
                 innlegg_dato: datetime = None,
                 innlegg_endret: datetime = None,
                 innlegg_treff: int = None,
                 blog_prefix: str = None,
                 blog_navn: str = None
                 ):
        self.innlegg_id = innlegg_id
        self.innlegg_tittel = innlegg_tittel
        self.innlegg_innhold = innlegg_innhold
        self.innlegg_dato = innlegg_dato
        self.innlegg_endret = innlegg_endret
        self.innlegg_treff = innlegg_treff
        self.blog_prefix = blog_prefix
        self.blog_navn = blog_navn
        self._kommentarer = None
        self._vedlegg = None
        self._tagger = None
        self._blog = None
        self._bruker = None

    @property
    def kommentarer(self) -> List[Kommentar]:
        if not self._kommentarer:
            self._kommentarer = Kommentar.get_all(self.innlegg_id)
        return self._kommentarer

    @property
    def tagger(self) -> List[Tagger]:
        if not self._tagger:
            self._tagger = Tagger.get_tags(self.innlegg_id)
        return self._tagger

    @property
    def vedlegg(self) -> List[Vedlegg]:
        if not self._vedlegg:
            self._vedlegg = Vedlegg.get_all(self.innlegg_id)
        return self._vedlegg

    @property
    def blog(self) -> Blog:
        if not self._blog:
            self._blog = Blog.get_one(self.blog_prefix)
        return self._blog

    @property
    def bruker(self) -> Bruker:
        if not self._bruker:
            self._bruker = Bruker.get_user_for_blog(self.blog_prefix)
        return self._bruker

    @property
    def url(self) -> str:
        return url_for("blog.vis_innlegg", blog_prefix=self.blog_prefix, innlegg_id=self.innlegg_id)

    @staticmethod
    def get_all(blog_navn: str) -> List["Innlegg"]:
        query = """
        select innlegg_id, 
               innlegg_tittel, 
               innlegg_innhold, 
               innlegg_dato, 
               innlegg_endret, 
               innlegg_treff,
               blog_prefix
        from innlegg where blog_prefix = %s and innlegg_dato > CURRENT_TIMESTAMP
        """

        db.cursor.execute(query, (blog_navn,))
        result = [Innlegg(*x) for x in db.cursor.fetchall()]
        return result

    @staticmethod
    def get_one(innlegg_id: int) -> "Innlegg":
        query = """
        select innlegg_id, 
               innlegg_tittel, 
               innlegg_innhold, 
               innlegg_dato, 
               innlegg_endret, 
               innlegg_treff,
               blog_prefix
        from innlegg where innlegg_id = %s
        """

        db.cursor.execute(query, (innlegg_id,))
        result = db.cursor.fetchone()
        if result:
            return Innlegg(*result)
        else:
            abort(404)

    @staticmethod
    def get_ten_newest() -> List["Innlegg"]:
        query = """
         select innlegg.innlegg_id, 
            innlegg_tittel, 
            innlegg_innhold, 
            innlegg_dato, 
            innlegg_endret, 
            innlegg_treff,
            innlegg.blog_prefix,
            blog.blog_navn
         from innlegg, blog where blog.blog_prefix = innlegg.blog_prefix order by innlegg_dato desc limit 10
         """

        db.cursor.execute(query)
        result = [Innlegg(*x) for x in db.cursor.fetchall()]
        return result

    @staticmethod
    def get_ten_most_hits() -> List["Innlegg"]:
        query = """
         select innlegg.innlegg_id, 
            innlegg_tittel, 
            innlegg_innhold, 
            innlegg_dato, 
            innlegg_endret, 
            innlegg_treff,
            innlegg.blog_prefix,
            blog.blog_navn
         from innlegg, blog where blog.blog_prefix = innlegg.blog_prefix order by innlegg_treff desc limit 10
         """

        db.cursor.execute(query)
        result = [Innlegg(*x) for x in db.cursor.fetchall()]
        return result

    @staticmethod
    def get_ten_most_commented() -> List["Innlegg"]:
        query = """
         select innlegg.innlegg_id, 
            innlegg_tittel, 
            innlegg_innhold, 
            innlegg_dato, 
            innlegg_endret, 
            innlegg_treff,
            innlegg.blog_prefix,
            blog.blog_navn
         from innlegg, kommentar, blog where blog.blog_prefix = innlegg.blog_prefix and innlegg.innlegg_id = kommentar.innlegg_id group by innlegg.innlegg_id order by COUNT(kommentar.kommentar_id) DESC limit 10
         """

        db.cursor.execute(query)
        result = [Innlegg(*x) for x in db.cursor.fetchall()]
        return result

    @staticmethod
    def update_hit(innlegg_id: int):
        query = """
        update innlegg set innlegg_treff=innlegg_treff+1 where innlegg_id = (%s);
        """
        db.cursor.execute(query, (innlegg_id,))
        db.connection.commit()

    @staticmethod
    def get_with_tag(tag_navn: str) -> List["Innlegg"]:
        query = """
        select innlegg.innlegg_id,
            innlegg_tittel,
            innlegg_innhold,
            innlegg_dato,
            innlegg_endret,
            innlegg_treff,
            innlegg.blog_prefix,
            blog.blog_navn
        from innlegg, blog, tag 
        where blog.blog_prefix = innlegg.blog_prefix 
            and tag.innlegg_id = innlegg.innlegg_id 
            and tag.tag_navn = %s order by innlegg_dato desc
        """
        db.cursor.execute(query, (tag_navn,))
        result = [Innlegg(*x) for x in db.cursor.fetchall()]
        return result

    @staticmethod
    def get_with_blog_prefix(blog_prefix: str) -> List["Innlegg"]:
        query = """
        select innlegg.innlegg_id,
            innlegg_tittel,
            innlegg_innhold,
            innlegg_dato,
            innlegg_endret,
            innlegg_treff,
            innlegg.blog_prefix,
            blog.blog_navn
        from innlegg 
            inner join blog on innlegg.blog_prefix = blog.blog_prefix 
        where blog.blog_prefix = %s 
        order by innlegg_dato desc 
        """
        db.cursor.execute(query, (blog_prefix,))
        result = [Innlegg(*x) for x in db.cursor.fetchall()]
        return result

    @staticmethod
    def search(search_string: str) -> List["Innlegg"]:
        query = """
        select innlegg.innlegg_id,
            innlegg_tittel,
            innlegg_innhold,
            innlegg_dato,
            innlegg_endret,
            innlegg_treff,
            innlegg.blog_prefix,
            blog.blog_navn
        from innlegg 
            inner join blog on innlegg.blog_prefix = blog.blog_prefix 
        where innlegg_innhold like CONCAT('%', %s, '%') 
           or innlegg_tittel like CONCAT('%', %s, '%') 
        """
        db.cursor.execute(query, (search_string, search_string))
        result = [Innlegg(*x) for x in db.cursor.fetchall()]
        return result

    def insert(self) -> "Innlegg":
        query = """
        insert into innlegg(innlegg_tittel, innlegg_innhold, blog_prefix)
        values (%s, %s, %s)
        """
        db.cursor.execute(query, (self.innlegg_tittel, self.innlegg_innhold, self.blog_prefix))
        db.connection.commit()

        return Innlegg.get_one(db.cursor.lastrowid)

    def update(self) -> "Innlegg":
        query = """
        update innlegg set innlegg_tittel = %s, innlegg_innhold = %s, innlegg_endret = CURRENT_TIMESTAMP
        where innlegg_id = %s
        """
        db.cursor.execute(query, (self.innlegg_tittel, self.innlegg_innhold, self.innlegg_id))
        db.connection.commit()

        return Innlegg.get_one(self.innlegg_id)

    def delete(self):
        query = """
        delete from innlegg 
        where innlegg_id = %s
        """
        delete_tags = """
        delete from tag
        where innlegg_id = %s
        """
        delete_comments = """
        delete from kommentar
        where innlegg_id = %s
        """
        delete_comment_log = """
        delete from kommentar_logg
        where innlegg_id = %s
        """
        try:
            db.cursor.execute(delete_tags, (self.innlegg_id,))
            db.cursor.execute(delete_comments, (self.innlegg_id,))
            db.cursor.execute(delete_comment_log, (self.innlegg_id,))
            db.cursor.execute(query, (self.innlegg_id,))
            db.connection.commit()
        except Error as err:
            db.connection.rollback()
            raise err

    def add_tag(self, tag_navn):
        tag = Tagger(tagnavn=tag_navn, innleggid=self.innlegg_id)
        tag.add_tag()

    def add_kommentar(self, kommentar_innhold, bruker_navn) -> Kommentar:
        kommentar = Kommentar(innhold=kommentar_innhold, brukernavn=bruker_navn, innlegg_id=self.innlegg_id)
        return kommentar.insert_kommentar()

blueprints/blog/views.py
from flask import Blueprint, abort, flash, redirect, render_template, url_for
from flask_login import current_user, login_required

from blueprints.blog.forms import InnleggForm, KommentarForm, BloggForm
from models.blog import Blog
from models.innlegg import Innlegg
from models.kommentar import Kommentar
from models.tag import Tagger

router = Blueprint('blog', __name__, url_prefix="/blog")


@router.route("/list_all")
def list_all_blogs():
    all_blogs = Blog.get_all()

    return render_template('bloglist.html', allblogs=all_blogs, heading="Alle blogger")


@router.route("/<blog_prefix>")
def show_blog(blog_prefix: str):
    posts_with_tag = Innlegg.get_with_blog_prefix(blog_prefix)
    blog = Blog.get_one(blog_prefix)
    if not blog:
        abort(404)
    if posts_with_tag and len(posts_with_tag) > 0:
        return render_template('index.html', blog=blog,
                               innlegg=posts_with_tag, heading=blog.blog_navn)
    if len(posts_with_tag) == 0:
        return render_template('index.html', blog=blog, innlegg=None, heading=blog.blog_navn)

    abort(404)


@router.route("/new_blog", methods=["GET", "POST"])
@login_required
def new_blog():
    form = BloggForm()
    if form.validate_on_submit():
        blog = Blog.get_one(form.blog_prefix.data)
        if blog:
            flash("Dette prefikset er allerede tatt", 'danger')
            return render_template('new_blog.html', form=form, heading="Opprett blogg")
        blog = Blog(blog_navn=form.blog_navn.data, blog_prefix=form.blog_prefix.data,
                    bruker_navn=current_user.brukernavn)
        blog.insert_blog()
        return redirect(url_for("hovedside.index"))

    return render_template('new_blog.html', form=form, heading="Opprett blogg")


@router.route("/<blog_prefix>/new", methods=["GET", "POST"])
@login_required
def nytt_innlegg(blog_prefix: str):
    form = InnleggForm()
    blog = Blog.get_one(blog_prefix)
    if blog.blog_bruker_navn != current_user.brukernavn:
        flash("Du må være eieren av en blog for å legge inn ett nytt innlegg!")
        return redirect(url_for("hovedside.index"))

    available_tags = Tagger.get_all_available_tags()

    if form.validate_on_submit():
        innlegg = Innlegg(innlegg_tittel=form.tittel.data, innlegg_innhold=form.innhold.data, blog_prefix=blog_prefix)
        innlegg = innlegg.insert()
        for tag in form.tagger.data:
            tag = Tagger(tagnavn=tag, innleggid=innlegg.innlegg_id)
            tag.add_tag()
        return redirect(url_for('blog.vis_innlegg', blog_prefix=blog_prefix, innlegg_id=innlegg.innlegg_id))
    for fieldName, error_messages in form.errors.items():
        for error_message in error_messages:
            flash(f"{fieldName}: {error_message}", "danger")
    return render_template("nytt_innlegg.html", form=form, blog_prefix=blog_prefix, available_tags=available_tags)


@router.route("/<blog_prefix>/<int:innlegg_id>/rediger", methods=["GET", "POST"])
@login_required
def rediger_innlegg(blog_prefix: str, innlegg_id: int):
    form = InnleggForm()
    blog = Blog.get_one(blog_prefix)
    if blog.blog_bruker_navn != current_user.brukernavn:
        abort(401)

    if form.validate_on_submit():
        innlegg = Innlegg.get_one(innlegg_id)
        innlegg.innlegg_tittel = form.tittel.data
        innlegg.innlegg_innhold = form.innhold.data
        innlegg = innlegg.update()
        tagger = [tag.tagnavn for tag in innlegg.tagger]
        for tag in form.tagger.data:
            if tag not in tagger:
                tag = Tagger(tagnavn=tag, innleggid=innlegg.innlegg_id)
                tag.add_tag()
        for tag in innlegg.tagger:
            if tag.tagnavn not in form.tagger.data:
                tag.delete_tag()
        return redirect(url_for('blog.vis_innlegg', blog_prefix=blog_prefix, innlegg_id=innlegg_id))

    for fieldName, error_messages in form.errors.items():
        for error_message in error_messages:
            flash(f"{fieldName}: {error_message}", "danger")

    innlegg = Innlegg.get_one(innlegg_id)
    form.tagger.data = [tag.tagnavn for tag in innlegg.tagger]
    form.tittel.data = innlegg.innlegg_tittel
    form.innhold.data = innlegg.innlegg_innhold

    available_tags = Tagger.get_all_available_tags_not_used_in_post(innlegg_id)

    return render_template("nytt_innlegg.html", form=form, blog_prefix=blog_prefix, available_tags=available_tags,
                           innlegg_id=innlegg_id)


@router.route("/<blog_prefix>/<int:innlegg_id>", methods=["GET", "POST"])
def vis_innlegg(blog_prefix: str, innlegg_id: int):
    innlegg = Innlegg.get_one(innlegg_id)

    if innlegg.blog_prefix != blog_prefix:
        abort(404)

    Innlegg.update_hit(innlegg_id)

    form = KommentarForm()
    if form.validate_on_submit():
        innlegg.add_kommentar(form.innhold.data, current_user.brukernavn)
        return redirect(url_for("blog.vis_innlegg", blog_prefix=blog_prefix, innlegg_id=innlegg_id))

    return render_template("innlegg.html", innlegg=innlegg, form=form)


@router.route("/<blog_prefix>/<int:innlegg_id>/slett")
def slett_innlegg(blog_prefix: str, innlegg_id: int):
    innlegg = Innlegg.get_one(innlegg_id)

    if innlegg.blog_prefix != blog_prefix:
        abort(404)

    innlegg.delete()
    flash("Innlegget er slettet!", 'success')

    return redirect(url_for("blog.show_blog", blog_prefix=blog_prefix))


@router.route("/slett_kommentar/<int:kommentar_id>")
def slett_kommentar(kommentar_id: int):
    kommentar = Kommentar.get_kommentar(kommentar_id)
    innlegg = Innlegg.get_one(kommentar.innlegg_id)
    if (kommentar.brukernavn == current_user.brukernavn) or (innlegg.bruker.brukernavn == current_user.brukernavn):
        kommentar.delete_kommentar()
        flash("Kommentar slettet!", "success")
        return redirect(innlegg.url)
    else:
        abort(401)

blueprints/hovedside/views.py
from flask import Blueprint, abort, render_template, request

from models.innlegg import Innlegg
from models.tag import Tagger

router = Blueprint('hovedside', __name__)


@router.route("/")
def index():
    new10 = Innlegg.get_ten_newest()
    if new10:
        return render_template('index.html',
                               innlegg=new10,
                               no_result_message="Ingen innlegg så langt...")


@router.route("/tag/<tag_navn>")
def tag(tag_navn: str):
    posts_with_tag = Innlegg.get_with_tag(tag_navn)
    return render_template('index.html',
                           innlegg=posts_with_tag,
                           no_result_message="Denne taggen har ingen innlegg...")


@router.route("/search", methods=["GET", "POST"])
def search():
    search_string = request.form.get("search-string", "")
    search_result = Innlegg.search(search_string)
    return render_template("index.html", innlegg=search_result,
                           no_result_message="Søket ga desverre ingen resultater...")


@router.route("/tag/list_all")
def list_all_tags():
    all_tags = Tagger.tag_usage()

    return render_template('taglist.html', alltags=all_tags, heading="Alle tagger")


@router.route("/most_views")
def most_hit_posts():
    most_hits = Innlegg.get_ten_most_hits()

    return render_template('index.html', innlegg=most_hits, heading="10 mest viste innlegg")


@router.route("/newest_posts")
def newest_posts():
    newest_posts = Innlegg.get_ten_newest()

    return render_template('index.html', innlegg=newest_posts, heading="10 nyeste innlegg")


@router.route("/most_comments")
def most_commented_posts():
    most_comments = Innlegg.get_ten_most_commented()

    return render_template('index.html', innlegg=most_comments, heading="10 mest engasjerende innlegg")

templates/401.html
{% extends "base.html" %}
{% block body %}
    <div class="four_o_four container">
        <div class="row justify-content-center">
            <div class="col-md-12 text-center">
                <img src="{{ url_for('static', filename='img/no-no-no.gif') }}" alt="no-no-no" height="500"/>
                <div class="mb-4 lead">Du har ikke tilgang til denne siden...</div>
                <a class="text-decoration-none" href="{{ url_for('hovedside.index') }}">
                    Gå til hovedsiden heller, det har du lov til! </a>
            </div>
        </div>
    </div>
{% endblock %}a

templates/innlegg.html
{% extends 'base.html' %}
{% block body %}
    <div class="container">
        <h1 class="display-1 mt-5 mb-3 text-center">{{ innlegg.innlegg_tittel }}</h1>

        <div class="tagger pb-4 text-center">
            {% for tag in innlegg.tagger %}
                <a href="{{ url_for('hovedside.tag', tag_navn=tag.tagnavn) }}"
                   class="badge border border-success text-success rounded-pill bg-white px-2 py-1 mr-3 text-decoration-none">{{ tag.tagnavn }}</a>
            {% endfor %}
        </div>

        <h5 class="text-center">
            Skrevet av:
            <small class="text-muted">{{ innlegg.bruker.fullt_navn }}</small>
            på:
            <small class="text-muted"><a
                    href="{{ url_for('blog.show_blog', blog_prefix=innlegg.blog.blog_prefix) }}">{{ innlegg.blog.blog_navn }}</a></small>
        </h5>
        <h6 class="text-center mb-4">
            <small class="text-muted">{{ innlegg.innlegg_dato }}</small>
            antall treff:
            <small class="text-muted">{{ innlegg.innlegg_treff }}</small>
        </h6>
        {% if current_user.brukernavn == innlegg.bruker.brukernavn %}
            <div class="d-flex flex-row justify-content-center mb-4">
                <a href="{{ url_for('blog.rediger_innlegg',blog_prefix=innlegg.blog_prefix, innlegg_id=innlegg.innlegg_id ) }}"
                   class="font-weight-bold link-success mx-2">
                    Rediger
                </a>
                <a href="#" class="font-weight-bold link-success mx-2" onclick="deleteQuestion()">Slett</a>
            </div>
        {% endif %}
        {{ innlegg.innlegg_innhold | safe }}
        <hr/>
        <h5 class="mt-4">Kommentarer:</h5>
        <div class="container my-5">
            <div class="row d-flex justify-content-center">
                <div class="col-md-8">
                    {% for kommentar in innlegg.kommentarer %}
                        <div class="card p-3 mt-2">
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="d-flex flex-row align-items-center">
                                    {% if kommentar.bruker.blog %}
                                        <a href="{{ url_for('blog.show_blog', blog_prefix=kommentar.bruker.blog.blog_prefix) }}"
                                           class="font-weight-bold link-primary">
                                            {{ kommentar.bruker.fullt_navn }}
                                        </a>
                                    {% else %}
                                        <span class="font-weight-bold text-primary">
                                        {{ kommentar.bruker.fullt_navn }}
                                         </span>
                                    {% endif %}
                                    <span>&nbsp;</span>
                                    {% if current_user.brukernavn == innlegg.blog.blog_bruker_navn or current_user.brukernavn == kommentar.brukernavn %}
                                        <small><a
                                                href="{{ url_for('blog.slett_kommentar', kommentar_id = kommentar.id) }}"
                                                class="font-weight-bold link-danger">Slett</a></small>
                                    {% endif %}
                                </div>
                                <small>{{ kommentar.dato }}</small>
                            </div>
                            <div class="action d-flex justify-content-between mt-2 align-items-center">
                                {{ kommentar.innhold }}
                            </div>
                        </div>
                    {% endfor %}
                    {% if current_user.is_authenticated %}
                        <div class="card p-3 mt-2">
                            <form method="POST">
                                {{ form.csrf_token }}
                                <div class="mb-3 form-floating">
                                    {{ form.innhold(class_="form-control post-comment", placeholder="Leave a comment here") }}
                                    {{ form.innhold.label }}
                                </div>
                                {{ form.submit(class_="btn btn-success") }}
                            </form>
                        </div>
                    {% else %}
                        <div class="text-center mt-3">
                            <a href="{{ url_for('auth.login', next=innlegg.url) }}"
                               class="link-success">Logg inn</a>
                            eller
                            <a href="{{ url_for('auth.register') }}" class="link-success">registrer deg</a>
                            for å legge igjen en kommentar
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <script src="{{ url_for('static', filename='ckeditor/plugins/codesnippet/lib/highlight/highlight.pack.js') }}"></script>
    <script>hljs.initHighlightingOnLoad();</script>
    <script>

        function deleteQuestion() {
            var r = confirm("Vil du virkelig slette innlegget?");
            if (r == true) {
                window.location.href = "{{ url_for('blog.slett_innlegg',blog_prefix=innlegg.blog_prefix, innlegg_id=innlegg.innlegg_id ) }}";
            }
        }
    </script>


{% endblock %}

templates/navbar.html
<nav class="navbar navbar-expand-lg fixed-top navbar-light bg-light shadow-sm justify-content-between p-0 px-4">
    <div class="container-fluid g-0">
        <a class="navbar-brand text-success ms-3 fs-3" href={{ url_for('hovedside.index') }}><img
                src="{{ url_for('static', filename='img/duckface.png') }}" alt="duckface" height="30"/> Le blöög</a>


        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mob-navbar"
                aria-label="Toggle">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="mob-navbar">
            <form class="d-flex ms-auto w-25" method="post" action="{{ url_for('hovedside.search') }}">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                <input class="form-control me-2" type="search" placeholder="Søk" name="search-string"
                       aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Søk</button>
            </form>
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{ url_for('blog.list_all_blogs') }}">
                        Blogger</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{ url_for('hovedside.list_all_tags') }}">
                        Tagger</a>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link active dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Innlegg
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{{ url_for('hovedside.most_hit_posts') }}">Flest
                            visninger</a></li>
                        <li><a class="dropdown-item" href="{{ url_for('hovedside.most_commented_posts') }}">Mest
                            engasjerende</a></li>
                        <li><a class="dropdown-item" href="{{ url_for('hovedside.newest_posts') }}">Nyeste</a></li>
                    </ul>
                </li>

                {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <div class="dropdown">
                            <a class="btn btn-outline-success dropdown-toggle mx-3" href="#" role="button"
                               id="dropdownMenuLink"
                               data-bs-toggle="dropdown" aria-expanded="false">
                                {{ current_user.brukernavn }}
                            </a>

                            <ul class="dropdown-menu dropdown-menu-end">
                                {% if current_user.blog %}
                                    <li><a class="dropdown-item"
                                           href="{{ url_for('blog.nytt_innlegg', blog_prefix = current_user.blog.blog_prefix) }}">
                                        Nytt Innlegg</a>
                                    </li>
                                {% endif %}

                                {% if current_user.blog %}
                                    <li><a class="dropdown-item"
                                           href="{{ url_for('blog.show_blog',blog_prefix=current_user.blog.blog_prefix) }}">
                                        Min blogg</a>
                                    </li>
                                {% else %}
                                    <li><a class="dropdown-item" href="{{ url_for('blog.new_blog') }}">Opprett
                                        blogg</a>
                                    </li>
                                {% endif %}

                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="{{ url_for('auth.logout') }}">Logg ut</a></li>
                            </ul>
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="btn btn-outline-success mx-1" href="{{ url_for('auth.register') }}">Ny bruker</a>
                    </li>
                    <li class="nav-item">
                        <a class="btn btn-outline-success mx-1" href="{{ url_for('auth.login', next=request.url) }}">Logg
                            inn</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/nytt_innlegg.html
{% extends "base.html" %}

{% block body %}
    {% if innlegg_id %}
        <h2 class="styled_heading display-3 text-center text-success py-4"> Rediger innlegg #{{ innlegg_id }}  </h2>
    {% else %}
        <h2 class="styled_heading display-3 text-center text-success py-4"> Nytt innlegg </h2>
    {% endif %}

    <div class="container mt-5">
        <div class="row align-items-center">
            <div class="card p-3 m-auto">
                {% if innlegg_id %}
                    <form method="POST"
                          action="{{ url_for('blog.rediger_innlegg', blog_prefix=blog_prefix, innlegg_id=innlegg_id) }}"
                          class="post-edit-form">
                {% else %}
                    <form method="POST" action="{{ url_for('blog.nytt_innlegg', blog_prefix=blog_prefix) }}"
                          class="post-edit-form">
                {% endif %}
                {{ form.csrf_token }}

                <div class="mb-3">
                    {{ form.tittel.label(class_="form-label") }}
                    {{ form.tittel(class_="form-control") }}
                </div>
                <div class="mb-3">
                    {{ form.innhold.label(class_="form-label") }}
                    {{ form.innhold(class_="form-control") }}
                </div>
                <div class="mb-3">
                    {{ form.tagger.label(class_="form-label") }}
                    {{ form.tagger(**{"class":"form-control", "data-role": "tagsinput", "hidden":"true" }) }}
                </div>
                <div class="row justify-content-end">
                    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                        <input type="button" value="Tilbake" onclick="history.back()"
                               class="btn btn-outline-success">
                        <input type="submit" value="Lagre" class="btn btn-success">
                    </div>
                </div>
                </form>
            </div>
        </div>
        <div class="mb-5">
            <h4>Tidligere brukte tagger:</h4>
            {% for tag in available_tags %}
                <span class="badge border border-success text-success rounded-pill bg-white p-2 m-2 text-decoration-none available-tag"
                      onclick="$('#tagger').tagsinput('add', '{{ tag }}');  $(this).hide();">{{ tag }}</span>
            {% endfor %}
        </div>
    </div>

    <script src="{{ url_for('static', filename='ckeditor/ckeditor.js') }}"></script>
    {{ ckeditor.config(name="innhold") }}
{% endblock %}